name: Docker CI for Sarcasm Detector

on:
  push:
    branches: [ main ]

jobs:
  build-model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install transformers torch joblib tiktoken protobuf sentencepiece

    - name: Run model training script
      run: python train_model.py

    - name: Upload model as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sentiment-model
        path: app/model/sentiment_pipeline.pkl

  build-and-test:
    needs: build-model
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download model artifact
      uses: actions/download-artifact@v4
      with:
        name: sentiment-model
        path: app/model/

    - name: Build Docker image
      run: docker build -t sarcasm-detector .

    - name: Run container
      run: docker run -d -p 8000:8000 --name detector sarcasm-detector

    - name: Wait for API to start
      run: sleep 10

    - name: Install requests to test API
      run: pip install requests

    - name: Run model test script
      run: python test_model.py

    - name: Stop container
      run: docker stop detector && docker rm detector